### ISSUE TITLE
Open issue on enquiry from another repo

### ISSUE THREAD

**Issue by BroVic** [BroVic/IntroR#1]
@obroma

Reference to **[this issue](https://github.com/NESREA/WMGtraining/issues/14)**:

What is *Workbook1practice*? A file, an object or a column in your data frame?

**Comment by obroma** [comment]
Workbook1practice is a column in data frame. i had earlier use scatter graph to plot it in R, but needed to see how it is represented in ts

**Comment by BroVic** [comment]
From your question, what you ran was `freqpolygon()` and not `ts()`. Anyway, in the case of the former, you must remember to attach the `mosaic` package, because that function does not exist in base R. If you were able to do a scatter plot with the same data, it shouldn't be a problem. To attach the package, you can run
```
library(mosaic)
```
As for the time series, apart from the data (i.e. your column) you must provide other arguments like `start`, `end` and `frequency`. You can quickly see the list of arguments for any function by calling `args()`, for example
```
args(ts)
```
In this instance, the output looks something like this:
```
function (data = NA, start = 1, end = numeric(), frequency = 1, 
    deltat = 1, ts.eps = getOption("ts.eps"), class = if (nseries > 
        1) c("mts", "ts", "matrix") else "ts", names = if (!is.null(dimnames(data))) colnames(data) else paste("Series", 
        seq(nseries)))
```
To have a more detailed understanding on what these mean, read the **Arguments** section of the documentation, which you can open by running the `?` function as follows:
```
?ts
```
Do note that many of the parameters already have default arguments i.e. `parameter = argument`. So you don't have to provide **ALL** arguments for a function. For instance you see `start = 1`; if you had data that starts from *January*, you could omit explicitly providing this argument since in a month-by-month time-series, January is represented by 1.
