### ISSUE TITLE
Cloned Document

### ISSUE THREAD

**Issue by Mgbeke** [BroVic/IntroR#2]
Good day Sir,

The directory has been cloned. It's quite interesting cos I thought that I had already downloaded and installed the Github for desktop not until I had to clone this document and it asked for me to move it to my desktop. 
Thank you for the docs and I look forward to hearing from you on the way forward.

Best regards 
Nnennaya Ogbonnaya

**Comment by BroVic** [comment]
Try out the exercises. 

Cheers!
